version: "3.7"

services:
  gateway:
    image: jhc/gateway:${TAG:-v1.0.0}
    build:
      context: ./gateway/
    restart: "unless-stopped"
    container_name: jhc-gateway
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"

  frontend:
    image: jhc/frontend:${TAG:-v1.0.0}
    build:
      context: ./frontend/
    restart: "unless-stopped"
    container_name: jhc-frontend
    environment:
      SPA_PATH: /openmrs/spa
      API_URL: /openmrs
      SPA_CONFIG_URLS: /openmrs/spa/jhc_config.json
      SPA_DEFAULT_LOCALE:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      timeout: 5s
    depends_on:
      - backend
    volumes:
      - ./frontend/jhc_config.json:/usr/share/nginx/html/jhc_config.json

  backend:
    image: jhc/backend:${TAG:-v1.0.0}
    build:
      context: .
    restart: "unless-stopped"
    container_name: jhc-backend
    depends_on:
      - db
    environment:
      OMRS_CONFIG_MODULE_WEB_ADMIN: "true"
      OMRS_CONFIG_AUTO_UPDATE_DATABASE: "true"
      OMRS_CONFIG_CREATE_TABLES: "true"
      OMRS_CONFIG_CONNECTION_SERVER: db
      OMRS_CONFIG_CONNECTION_DATABASE: openmrs
      OMRS_CONFIG_CONNECTION_USERNAME: ${OPENMRS_DB_USER:-openmrs}
      OMRS_CONFIG_CONNECTION_PASSWORD: ${OPENMRS_DB_PASSWORD:-openmrs}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/openmrs"]
      timeout: 5s
    volumes:
      - openmrs-data:/openmrs/data
      - ./distro/configuration/:/openmrs/distribution/openmrs_config
    env_file:
      - .env

  # MariaDB
  db:
    image: mariadb:10.11.7
    restart: "unless-stopped"
    container_name: jhc-mariadb
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci"
    healthcheck:
      test: "mysql --user=${OMRS_DB_USER:-openmrs} --password=${OMRS_DB_PASSWORD:-openmrs} --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 5
    environment:
      MYSQL_DATABASE: openmrs
      MYSQL_USER: ${OMRS_DB_USER:-openmrs}
      MYSQL_PASSWORD: ${OMRS_DB_PASSWORD:-openmrs}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-openmrs}
    volumes:
      - db-data:/var/lib/mysql

volumes:
  openmrs-data: ~
  db-data: ~
